/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.rAndD;

import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import ecosystemworkflow.Organization.DrugProductionOrganization;
import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.pharma.User.DrugProductionManagerWorkAreaJPanel;

/**
 *
 * @author gunav
 */
public class RAndDMainJPanel extends javax.swing.JPanel {

    
    private JPanel workArea;
    private UserAccount UserAccount;
    private Organization org;
    private Enterprise Enterprise;
    private EcoSystem ESystem;


    public RAndDMainJPanel(JPanel workArea,UserAccount userAccount,Organization org,Enterprise enterprise,EcoSystem eSystem) {
        initComponents();
        this.workArea=workArea;
        this.UserAccount=userAccount;
        this.org= org;
        this.Enterprise=enterprise;
        this.ESystem=eSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageResearch = new javax.swing.JButton();
        brnRequest = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageResearch.setBackground(new java.awt.Color(255, 255, 255));
        btnManageResearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageResearch.setText("Manage Research And Development");
        btnManageResearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageResearchActionPerformed(evt);
            }
        });
        add(btnManageResearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 135, -1, 81));

        brnRequest.setBackground(new java.awt.Color(255, 255, 255));
        brnRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        brnRequest.setText("Request Clinical Trails");
        brnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRequestActionPerformed(evt);
            }
        });
        add(brnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 243, 283, 81));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Research and Outcomes");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (2).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void brnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRequestActionPerformed
        // TODO add your handling code here:
        RequestClinicalTrialJPanel dMW = new RequestClinicalTrialJPanel(workArea, UserAccount,org, Enterprise,ESystem);
        workArea.add("DrugProductionManagerWorkAreaJPanel", dMW);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_brnRequestActionPerformed

    private void btnManageResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageResearchActionPerformed
        // TODO add your handling code here:
        RAndDManagementPanel dMW = new RAndDManagementPanel(workArea, ESystem, Enterprise );
        workArea.add("DrugProductionManagerWorkAreaJPanel", dMW);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageResearchActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton brnRequest;
    private javax.swing.JButton btnManageResearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
