/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.bloodSupply;

import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class BloodBankOrganizationManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodBankOrganizationManagementPanel
     */
    private JPanel workArea;
    private EcoSystem ecosystem;
    private Enterprise enterprise;
    
    /**
     * Creates new form CareerServiceAdminUI
     */
    public BloodBankOrganizationManagementPanel(JPanel workArea, EcoSystem ecosystem,Enterprise enterprise) {
        initComponents();
        this.workArea = workArea;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUserAcc = new javax.swing.JButton();
        btnManageOrg = new javax.swing.JButton();
        btnEmploye = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUserAcc.setBackground(new java.awt.Color(255, 255, 255));
        btnUserAcc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUserAcc.setText("Manage Organization Employees User Accounts");
        btnUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccActionPerformed(evt);
            }
        });
        add(btnUserAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 273, -1, 58));

        btnManageOrg.setBackground(new java.awt.Color(255, 255, 255));
        btnManageOrg.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 121, 317, 58));

        btnEmploye.setBackground(new java.awt.Color(255, 255, 255));
        btnEmploye.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnEmploye.setText("Manage Organization Employees");
        btnEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeActionPerformed(evt);
            }
        });
        add(btnEmploye, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 197, 317, 58));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Blood Bank");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Blood Bank Oranization Management ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (4).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccActionPerformed
        // TODO add your handling code here:
        ManageBloodBankUserAccounts mHCU = new ManageBloodBankUserAccounts(workArea, enterprise);
        workArea.add("ManageBloodBankUserAccounts", mHCU);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnUserAccActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:
        ManageBloodBankOrganization mHCO = new ManageBloodBankOrganization(workArea, enterprise.getOrganizationDirectory());
        workArea.add("ManageBloodBankOrganization", mHCO);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeActionPerformed
        // TODO add your handling code here:
        ManageBloodBankEmployee mHCE = new ManageBloodBankEmployee(workArea, enterprise.getOrganizationDirectory());
        workArea.add("ManageHealthCareEmployee", mHCE);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnEmployeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmploye;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnUserAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
