/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HealthCare.User;

import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.ClinicalTrialProtocolRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class ClinicalTrialDataCollectionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicalTrialDataCollectionJPanel
     */
    private UserAccount userAccount;
    private Organization organization;
    private JPanel container;
    private ClinicalTrialProtocolRequest request;
    
    public ClinicalTrialDataCollectionJPanel(JPanel container, UserAccount account, 
            Organization organization, ClinicalTrialProtocolRequest request) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        this.request = request;
        populateTrialDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTrialName = new javax.swing.JTextField();
        txtDrugName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservations = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trail Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 138, -1, -1));

        txtTrialName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(txtTrialName, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 135, 152, -1));

        txtDrugName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDrugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugNameActionPerformed(evt);
            }
        });
        add(txtDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 163, 152, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Drug Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 166, -1, -1));

        txtPhase.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(txtPhase, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 191, 152, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phase");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 194, -1, -1));

        txtStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 219, 152, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 222, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 364, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Observations:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 260, -1, -1));

        txtObservations.setColumns(20);
        txtObservations.setRows(5);
        txtObservations.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtObservations);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clinical Trails");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Data Collection");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (2).jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtObservations.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add trial observations");
            return;
        }

        request.setStatus("Data Collected");
        JOptionPane.showMessageDialog(null, "Trial data submitted successfully");
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextArea txtObservations;
    private javax.swing.JTextField txtPhase;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTrialName;
    // End of variables declaration//GEN-END:variables

     private void populateTrialDetails() {
        txtTrialName.setText(request.getTrialName());
        txtDrugName.setText(request.getDrugName());
        txtPhase.setText(request.getPhase());
        txtStatus.setText(request.getStatus());
    }
}
