/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HealthCare.User;

//import UserInterface.HeathCare.User.ViewDrugRequestsJPanel;
import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import ecosystemworkflow.Enterprise.PharmaceuticalEnterprise;
import ecosystemworkflow.Network.Network;
import ecosystemworkflow.Organization.DrugProductionOrganization;
import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.DrugProductionRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class RequestDrugProductionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestDrugProductionJPanel
     */
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private JPanel container;

    /**
     * Creates new form RequestDrugProductionJPanel
     */
    public RequestDrugProductionJPanel(JPanel container, UserAccount account,
            Organization organization, Enterprise enterprise, EcoSystem system) {

        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Normal");
        model.addElement("Urgent");
        model.addElement("Emergency");
        cmbPriority.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSubmit = new javax.swing.JButton();
        labelDrugName = new javax.swing.JLabel();
        txtDrugName = new javax.swing.JTextField();
        labelQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        cmbPriority = new javax.swing.JComboBox<>();
        buttonViewReq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSubmit.setBackground(new java.awt.Color(255, 255, 255));
        buttonSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        buttonSubmit.setText("Submit Request");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        add(buttonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 294, 146, -1));

        labelDrugName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelDrugName.setForeground(new java.awt.Color(255, 255, 255));
        labelDrugName.setText("Drug Name");
        add(labelDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 177, -1, -1));

        txtDrugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugNameActionPerformed(evt);
            }
        });
        add(txtDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 172, 118, -1));

        labelQuantity.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantity.setText("Quantity");
        add(labelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 207, -1, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 202, 118, -1));

        lblStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Priority");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 244, -1, -1));

        cmbPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 238, 118, -1));

        buttonViewReq.setBackground(new java.awt.Color(255, 255, 255));
        buttonViewReq.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        buttonViewReq.setText("View Requests");
        buttonViewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewReqActionPerformed(evt);
            }
        });
        add(buttonViewReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 294, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Drug Production");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 88, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (6).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        if(txtDrugName.getText().isEmpty() || txtQuantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all details");
            return;
        }

        try {
            // Find drug production organization first
            // Find pharmaceutical enterprise first
            PharmaceuticalEnterprise pharma = null;
            for(Network network : system.getNetworks()) {
                for(Enterprise ent : network.getEnterprises().getEnterpriseList()) {
                    if(ent instanceof PharmaceuticalEnterprise) {
                        pharma = (PharmaceuticalEnterprise)ent;
                        break;
                    }
                }
            }

            // Then find drug production organization
            Organization drugProductionOrg = null;
            if(pharma != null) {
                for(Organization org : pharma.getOrganizationDirectory().getOrganizations()) {
                    if(org instanceof DrugProductionOrganization) {
                        drugProductionOrg = org;
                        System.out.println("Found Drug Production Organization");
                        break;
                    }
                }
            }
            if(drugProductionOrg == null) {
                System.out.println("Drug Production Organization not found");
                return;
            }

            if(drugProductionOrg != null){
                // Create and initialize request
                DrugProductionRequest request = new DrugProductionRequest();
                request.setDrugName(txtDrugName.getText().trim());
                request.setQuantity(Integer.parseInt(txtQuantity.getText()));
                request.setUrgency((String) cmbPriority.getSelectedItem());
                request.setStatus("Requested");
                request.setSender(userAccount);
                request.setDateOfRequest(new Date());
                request.setProductionStatus("Requested");

                // Add request to work queues
                drugProductionOrg.getWorkRequestList().getWorkRequests().add(request);
                userAccount.getWorkQueue().getWorkRequests().add(request);
                system.getWorkRequestList().getWorkRequests().add(request);

                JOptionPane.showMessageDialog(null, "Request sent successfully");
                clearForm();
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter quantity in correct format");
        }

    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void txtDrugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugNameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void buttonViewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewReqActionPerformed
        //    Organization drugProductionOrg = null;
        //    for(Organization org : enterprise.getOrganizationDirectory().getOrganizations()) {
            //        if(org instanceof DrugProductionOrganization) {
                //            drugProductionOrg = org;
                //            break;
                //        }
            //    }
        //
        //    if(drugProductionOrg == null) {
            //        // If organization not found, create it
            //        drugProductionOrg = enterprise.getOrganizationDirectory()
            //            .createOrganization(Organization.OrganizationType.DrugProductionOrganization, "Drug Production");
            //        enterprise.getOrganizationDirectory().getOrganizations().add(drugProductionOrg);
            //    }
        //
        //    // Now create view panel with the found/created organization
        //    ViewDrugRequestsJPanel viewPanel = new ViewDrugRequestsJPanel(container, userAccount,
            //        drugProductionOrg, enterprise, system);
        //    container.add("ViewDrugRequests", viewPanel);
        //    CardLayout layout = (CardLayout) container.getLayout();
        //    layout.next(container);
    }//GEN-LAST:event_buttonViewReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JButton buttonViewReq;
    private javax.swing.JComboBox<String> cmbPriority;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelDrugName;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables


       private void clearForm() {
        txtDrugName.setText("");
        txtQuantity.setText("");
        cmbPriority.setSelectedIndex(0);
    }
}
