/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.logistics;

import ui.bloodSupply.*;
import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class LogisticsManegement extends javax.swing.JPanel {

    /**
     * Creates new form BloodBankOrganizationManagementPanel
     */
    private JPanel workArea;
    private EcoSystem ecosystem;
    private Enterprise enterprise;
    
    /**
     * Creates new form CareerServiceAdminUI
     */
    public LogisticsManegement(JPanel workArea, EcoSystem ecosystem,Enterprise enterprise) {
        initComponents();
        this.workArea = workArea;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUserAcc = new javax.swing.JButton();
        btnManageOrg = new javax.swing.JButton();
        btnEmploye = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUserAcc.setBackground(new java.awt.Color(255, 255, 255));
        btnUserAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserAcc.setText("Manage Organization Employees User Accounts");
        btnUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccActionPerformed(evt);
            }
        });
        add(btnUserAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 374, 58));

        btnManageOrg.setBackground(new java.awt.Color(255, 255, 255));
        btnManageOrg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 374, 58));

        btnEmploye.setBackground(new java.awt.Color(255, 255, 255));
        btnEmploye.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmploye.setText("Manage Organization Employees");
        btnEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeActionPerformed(evt);
            }
        });
        add(btnEmploye, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 374, 58));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Logistics");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (5).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccActionPerformed
        // TODO add your handling code here:
        ManageLogisticsUserAccounts mHCU = new ManageLogisticsUserAccounts(workArea, enterprise);
        workArea.add("ManageLogisticsUserAccounts", mHCU);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnUserAccActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:
        ManageLogisticsOrganization mHCO = new ManageLogisticsOrganization(workArea, enterprise.getOrganizationDirectory());
        workArea.add("ManageLogisticsOrganization", mHCO);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeActionPerformed
        // TODO add your handling code here:
        ManageLogisticsEmployee mHCE = new ManageLogisticsEmployee(workArea, enterprise.getOrganizationDirectory());
        workArea.add("ManageLogisticsEmployee", mHCE);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnEmployeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmploye;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnUserAcc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
