/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HealthCare;

import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.ClinicalTrialProtocolRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class ClinicalTrialReviewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicalTrialReviewJPanel
     */
    private UserAccount userAccount;
    private Organization organization;
    private JPanel container;
    private ClinicalTrialProtocolRequest request;
    
    public ClinicalTrialReviewJPanel(JPanel container, UserAccount account, 
            Organization organization, ClinicalTrialProtocolRequest request) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        this.request = request;
        populateRequestDetails();
    }
    
     private void populateRequestDetails() {
        txtTrialName.setText(request.getTrialName());
        txtDrugName.setText(request.getDrugName());
        txtPhase.setText(request.getPhase());
        txtRequiredPatients.setText(String.valueOf(request.getRequiredPatients()));
        txtComments.setText(request.getDescription());
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPhase = new javax.swing.JTextField();
        txtRequiredPatients = new javax.swing.JTextField();
        txtDrugName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTrialName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbStudyType = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtComments.setColumns(20);
        txtComments.setRows(5);
        txtComments.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(txtComments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 296, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clinical Trail Review");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phase:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 134, -1, -1));

        btnSubmit1.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit1.setText("Reject");
        btnSubmit1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });
        add(btnSubmit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 50, 20));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Required Patients:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 260, -1, -1));

        txtPhase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        add(txtPhase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 129, 151, -1));

        txtRequiredPatients.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        add(txtRequiredPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 255, 152, -1));

        txtDrugName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        add(txtDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 214, 152, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Comments:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 296, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Drug Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 219, -1, -1));

        txtTrialName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        add(txtTrialName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 88, 151, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trail Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 93, -1, -1));

        cmbStudyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudyType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        add(cmbStudyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 151, -1));

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setText("Approve");
        btnSubmit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 79, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Study Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 177, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (1).jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 740, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        // TODO add your handling code here:
        if(txtComments.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add rejection comments");
            return;
        }

        request.setStatus("Rejected");
        request.setDateOfResolving(new Date());

        JOptionPane.showMessageDialog(null, "Trial protocol rejected");
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnSubmit1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(txtComments.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add review comments");
            return;
        }

        try {
            request.setStatus("Approved");
            request.setDateOfResolving(new Date());

            JOptionPane.showMessageDialog(null, "Trial protocol approved");
            container.remove(this);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.previous(container);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating status: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JComboBox<String> cmbStudyType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtPhase;
    private javax.swing.JTextField txtRequiredPatients;
    private javax.swing.JTextField txtTrialName;
    // End of variables declaration//GEN-END:variables
}
