/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HealthCare;

import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.ClinicalTrialProtocolRequest;
import ecosystemworkflow.WorkFlow.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gunav
 */
public class HospitalTrialParticipantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalTrialParticipantJPanel
     */
    private UserAccount userAccount;
    private Organization organization;
    private JPanel container;
    
    public HospitalTrialParticipantJPanel(JPanel container, UserAccount account, 
            Organization organization) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrials = new javax.swing.JTable();
        btnEnroll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblTrials.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblTrials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Trail ID", "Trail Name", "Drug Name", "Phase", "Required Patients", "Trail Start Date"
            }
        ));
        jScrollPane1.setViewportView(tblTrials);

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 670, 121));

        btnEnroll.setBackground(new java.awt.Color(255, 255, 255));
        btnEnroll.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnEnroll.setText("Enroll");
        btnEnroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 59, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hospital Trail Participant");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 13, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        int selectedRow = tblTrials.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a trial");
            return;
        }

        ClinicalTrialProtocolRequest request = (ClinicalTrialProtocolRequest)
        tblTrials.getValueAt(selectedRow, 0);

        request.setStatus("Patient Enrolled");
        populateTable();
        JOptionPane.showMessageDialog(null, "Patient enrolled in trial");

    }//GEN-LAST:event_btnEnrollActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTrials;
    // End of variables declaration//GEN-END:variables
    
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblTrials.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkRequestList().getWorkRequests()) {
            if(request instanceof ClinicalTrialProtocolRequest) {
                ClinicalTrialProtocolRequest tr = (ClinicalTrialProtocolRequest) request;
                if(tr.getStatus().equals("Approved")) {
                    Object[] row = new Object[6];
                    row[0] = tr;
                    row[1] = tr.getTrialName();
                    row[2] = tr.getDrugName();
                    row[3] = tr.getPhase();
                    row[4] = tr.getRequiredPatients();
                    row[5] = tr.getTrialStartDate();
                    model.addRow(row);
                }
            }
        }
    }
    
}
