/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.pharma.User;

import ecosystemworkflow.Enterprise.Enterprise;
import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.Organization.QualityControlAndAssuranceOrganization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.DrugProductionRequest;
import ecosystemworkflow.WorkFlow.QualityControlAndAssuranceRequest;
import ecosystemworkflow.WorkFlow.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gunav
 */
public class DrugProductionManagerWorkAreaJPanel  extends javax.swing.JPanel {

    /**
     * Creates new form ViewReceivedRequestsJPanel
     */
     private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private JPanel container;
    
    public DrugProductionManagerWorkAreaJPanel(JPanel container, UserAccount account, 
            Organization organization, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        populateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrugRequests = new javax.swing.JTable();
        btnProces = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDrugRequests1 = new javax.swing.JTable();
        btnProces1 = new javax.swing.JButton();

        tblDrugRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Drug Name", "Requested Quantity", "Status", "Request Date", "Expected Delivery Date", "Priority", "Sender "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDrugRequests);

        btnProces.setText("Process Request");
        btnProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesActionPerformed(evt);
            }
        });

        tblDrugRequests1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Drug Name", "Requested Quantity", "Status", "Request Date", "Expected Delivery Date", "Priority", "Sender "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDrugRequests1);

        jScrollPane5.setViewportView(jScrollPane3);

        btnProces1.setText("back");
        btnProces1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProces1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProces1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnProces)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnProces1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnProces)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugRequests.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request");
            return;
        }
        
        DrugProductionRequest request = (DrugProductionRequest)
            tblDrugRequests.getValueAt(selectedRow, 0);
            
        // Create QA request
        QualityControlAndAssuranceRequest qaRequest = new QualityControlAndAssuranceRequest();
        qaRequest.setMessage("QA Request for " + request.getDrugName());
        qaRequest.setSender(userAccount);
        qaRequest.setBatchNumber("BATCH-" + System.currentTimeMillis());
        qaRequest.setDrugName(request.getDrugName());
        qaRequest.setBatchSize(request.getQuantity());
        qaRequest.setStatus("Pending QA");
        qaRequest.setManufacturingDate(new Date());
        
        // Find QA organization and route request
        Organization qaOrg = null;
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizations()) {
            if(org instanceof QualityControlAndAssuranceOrganization) {
                qaOrg = org;
                break;
            }
        }
        
        if(qaOrg != null) {
            qaOrg.getWorkRequestList().addWorkRequest(qaRequest);
            request.setStatus("In QA Testing");
            JOptionPane.showMessageDialog(null, "Sent to QA for testing");
            populateTable();
        }
    }//GEN-LAST:event_btnProcesActionPerformed

    private void btnProces1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProces1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnProces1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProces;
    private javax.swing.JButton btnProces1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblDrugRequests;
    private javax.swing.JTable tblDrugRequests1;
    // End of variables declaration//GEN-END:variables

    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDrugRequests1.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkRequestList().getWorkRequests()) {
            if(request instanceof DrugProductionRequest) {
                DrugProductionRequest dr = (DrugProductionRequest) request;
                if(dr.getStatus().equals("Pending")) {
                    Object[] row = new Object[6];
                    row[0] = dr;
                    row[1] = dr.getDrugName();
                    row[2] = dr.getQuantity();
                    row[3] = dr.getUrgency();
                    row[4] = dr.getStatus();
                    row[5] = dr.getDateOfRequest();
                    model.addRow(row);
                }
            }
        }
    }
    
}
