/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.pharma.QA;

import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import ecosystemworkflow.Network.Network;
import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.Organization.TransportOrganization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.QualityControlAndAssuranceRequest;
import ecosystemworkflow.WorkFlow.TransportOrganizationRequest;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class ProcessQARequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessQARequestJPanel
     */
    private UserAccount userAccount;
    private Organization organization;
    private JPanel container;
    private QualityControlAndAssuranceRequest request;
    private EcoSystem system;
    
    public ProcessQARequestJPanel(JPanel container, UserAccount account, 
            Organization organization, QualityControlAndAssuranceRequest request, EcoSystem system) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        this.request = request;
        this.system = system;
        
        
        populateRequestDetails();
        setupGradeComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtManufacturer = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        txtBatchNum = new javax.swing.JTextField();
        cmbQuality = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        labelDrugName = new javax.swing.JLabel();
        txtDrugName = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        lblQualityGrade = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        chkPassed = new javax.swing.JCheckBox();
        lblBatchNum = new javax.swing.JLabel();
        btnUpdateStatus = new javax.swing.JButton();
        txtBatchSize = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCommentsArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtManufacturer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        add(txtManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 335, 117, -1));

        lblManufacturer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblManufacturer.setText("Manufacturer:");
        add(lblManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 339, -1, -1));

        lblComments.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblComments.setText("Comments:");
        add(lblComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 382, -1, -1));

        txtBatchNum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        txtBatchNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchNumActionPerformed(evt);
            }
        });
        add(txtBatchNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 180, 118, -1));

        cmbQuality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbQuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 180, 80, -1));

        lblStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblStatus.setText("Status:");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 304, -1, -1));

        labelDrugName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelDrugName.setText("Drug Name:");
        add(labelDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 229, -1, -1));

        txtDrugName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        txtDrugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugNameActionPerformed(evt);
            }
        });
        add(txtDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 225, 118, -1));

        txtStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 300, 117, -1));

        lblQualityGrade.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblQualityGrade.setText("Quality Grade:");
        add(lblQualityGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 186, -1, -1));

        labelQuantity.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelQuantity.setText("Batch Size:");
        add(labelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 264, -1, -1));

        chkPassed.setBackground(new java.awt.Color(255, 255, 255));
        chkPassed.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkPassed.setText("Pass");
        chkPassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPassedActionPerformed(evt);
            }
        });
        add(chkPassed, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 60, -1));

        lblBatchNum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblBatchNum.setText("Batch Number:");
        add(lblBatchNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 186, -1, -1));

        btnUpdateStatus.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUpdateStatus.setText("Update");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });
        add(btnUpdateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 100, -1));

        txtBatchSize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        txtBatchSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchSizeActionPerformed(evt);
            }
        });
        add(txtBatchSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 260, 118, -1));

        txtCommentsArea.setColumns(20);
        txtCommentsArea.setRows(5);
        txtCommentsArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jScrollPane1.setViewportView(txtCommentsArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 382, 232, 96));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pharmaceuticals");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QA Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 75, -1, -1));

        backBtn2.setBackground(new java.awt.Color(255, 255, 255));
        backBtn2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backBtn2.setText("Back");
        backBtn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        add(backBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 109, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Untitled design (3).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBatchNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchNumActionPerformed

    private void txtDrugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugNameActionPerformed

    private void chkPassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPassedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPassedActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
        if(txtCommentsArea.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add inspection comments");
            return;
        }

        try {
            request.setInspectorComments(txtCommentsArea.getText().trim());
            request.setQualityGrade(cmbQuality.getSelectedItem().toString());
            request.setPassedQualityCheck(chkPassed.isSelected());

            if(request.isPassedQualityCheck()) {
                TransportOrganizationRequest transportRequest = new TransportOrganizationRequest();
                transportRequest.setMessage("Transport for " + request.getBatchNumber());
                transportRequest.setSender(userAccount);
                transportRequest.setItemType(request.getDrugName());
                transportRequest.setQuantity(request.getBatchSize());
                transportRequest.setStatus("Pending Pickup");

                Organization transportOrg = null;
                for(Network network : system.getNetworks()) {
                    for(Enterprise ent : network.getEnterprises().getEnterpriseList()) {
                        for(Organization org : ent.getOrganizationDirectory().getOrganizations()) {
                            if(org instanceof TransportOrganization) {
                                transportOrg = org;
                                break;
                            }
                        }
                    }
                }

                if(transportOrg != null) {
                    transportOrg.getWorkRequestList().addWorkRequest(transportRequest);
                    request.setStatus("Awaiting Transport");
                    JOptionPane.showMessageDialog(null, "QA Passed - Transport request created");
                }
            } else {
                request.setStatus("Failed QA Check");
                JOptionPane.showMessageDialog(null, "QA Failed - Drug production needs revision");
            }

            container.remove(this);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.previous(container);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating status: " + e.getMessage());
        }

    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void txtBatchSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchSizeActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        // TODO add your handling code here:

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JCheckBox chkPassed;
    private javax.swing.JComboBox<String> cmbQuality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDrugName;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel lblBatchNum;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblQualityGrade;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtBatchNum;
    private javax.swing.JTextField txtBatchSize;
    private javax.swing.JTextArea txtCommentsArea;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void setupGradeComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("A");
        model.addElement("B");
        model.addElement("C");
        model.addElement("D");
        model.addElement("F");
        cmbQuality.setModel(model);
    }
    
    private void populateRequestDetails() {
        txtBatchNum.setText(request.getBatchNumber());
        txtDrugName.setText(request.getDrugName());
        txtBatchSize.setText(String.valueOf(request.getBatchSize()));
        txtManufacturer.setText(request.getSender().getEmployee().getName());
    }
}
