/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HeathCare.User;

import UserInterface.HeathCare.*;
import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.DrugProductionRequest;
import ecosystemworkflow.WorkFlow.WorkRequest;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gunav
 */
public class ViewDrugRequestsJPanel extends javax.swing.JPanel {
    
    JPanel container;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    EcoSystem system;
    /**
     * Creates new form ViewDrugRequestsJPanel
     */
    public ViewDrugRequestsJPanel( JPanel container, UserAccount userAccount, 
           Organization organization,Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateRequestTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUpdateReq = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugRequests = new javax.swing.JTable();
        btnDeleteReq = new javax.swing.JButton();

        buttonUpdateReq.setText("Update Request");
        buttonUpdateReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateReqActionPerformed(evt);
            }
        });

        tblDrugRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Drug Name", "Requested Quantity", "Status", "Request Date", "Expected Delivery Date", "Priority", "Sender "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugRequests);

        jScrollPane2.setViewportView(jScrollPane1);

        btnDeleteReq.setText("Delete Request");
        btnDeleteReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonUpdateReq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteReq)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdateReq)
                    .addComponent(btnDeleteReq))
                .addContainerGap(458, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateReqActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonUpdateReqActionPerformed

    private void btnDeleteReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReqActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugRequests.getSelectedRow();
    if(selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a request to cancel");
        return;
    }
    
    DefaultTableModel model = (DefaultTableModel) tblDrugRequests.getModel();
    DrugProductionRequest request = (DrugProductionRequest)model.getValueAt(selectedRow, 0);
    
    // Only allow cancellation if request is not already processed
    if(request.getStatus().equals("Completed") || 
       request.getStatus().equals("Rejected") ||
       request.getStatus().equals("In Production")) {
        JOptionPane.showMessageDialog(this, 
            "Cannot cancel request that is already " + request.getStatus());
        return;
    }
    
    int response = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to cancel this request?", 
        "Confirm Cancellation", 
        JOptionPane.YES_NO_OPTION);
        
    if(response == JOptionPane.YES_OPTION) {
        request.setStatus("Cancelled");
        populateRequestTable();
        JOptionPane.showMessageDialog(this, "Request cancelled successfully!");
    }
    }//GEN-LAST:event_btnDeleteReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteReq;
    private javax.swing.JButton buttonUpdateReq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDrugRequests;
    // End of variables declaration//GEN-END:variables


     private void populateRequestTable() {
         
          if(organization == null || organization.getWorkRequestList() == null) {
        return;
    }
        DefaultTableModel model = (DefaultTableModel) tblDrugRequests.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkRequestList().getWorkRequests()) {
            if(request instanceof DrugProductionRequest) {
                DrugProductionRequest drugRequest = (DrugProductionRequest) request;
                Object[] row = new Object[8];
                row[0] = drugRequest;
                row[1] = drugRequest.getDrugName();
                row[2] = drugRequest.getQuantity();
                row[3] = drugRequest.getUrgency();
                row[4] = drugRequest.getStatus();
                row[5] = drugRequest.getSender().getEmployee().getEmpolyeeName();
                row[6] = drugRequest.getDateOfRequest();
                row[7] = calculateExpectedDelivery(drugRequest);
                model.addRow(row);
            }
        }
    }
    
    private Date calculateExpectedDelivery(DrugProductionRequest request) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(request.getDateOfRequest());
        
        switch(request.getUrgency()) {
            case "Emergency": cal.add(Calendar.HOUR_OF_DAY, 2); break;
            case "Urgent": cal.add(Calendar.HOUR_OF_DAY, 5); break;
            default: cal.add(Calendar.DAY_OF_MONTH, 2);
        }
        
        return cal.getTime();
    }
}
