/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Pharmaceutical;

import ecosystemworkflow.EcoSystem;
import ecosystemworkflow.Enterprise.Enterprise;
import ecosystemworkflow.Organization.Organization;
import ecosystemworkflow.Organization.QualityControlAndAssuranceOrganization;
import ecosystemworkflow.Role.QualityAnalystRole;
import ecosystemworkflow.UserAccount.UserAccount;
import ecosystemworkflow.WorkFlow.DrugProductionRequest;
import ecosystemworkflow.WorkFlow.QualityControlAndAssuranceRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gunav
 */
public class ProcessDrugRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessDrugRequestsPanel
     */
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private JPanel container;
    private DrugProductionRequest request;
    
    public ProcessDrugRequestsPanel(JPanel container, UserAccount account, 
            Organization organization, Enterprise enterprise, EcoSystem system, DrugProductionRequest request) {
        initComponents();
        this.container = container;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        labelDrugName = new javax.swing.JLabel();
        txtDrugName = new javax.swing.JTextField();
        btnSendToQA = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        buttonRequest2 = new javax.swing.JButton();
        txtPriority = new javax.swing.JTextField();
        lblBatchNum = new javax.swing.JLabel();
        txtBatchNum = new javax.swing.JTextField();

        labelQuantity.setText("Quantity");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        lblStatus.setText("Priority");

        labelDrugName.setText("Drug Name");

        txtDrugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugNameActionPerformed(evt);
            }
        });

        btnSendToQA.setText("Send to QA");
        btnSendToQA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToQAActionPerformed(evt);
            }
        });

        btnBack.setText("back");

        buttonRequest2.setText("View QA requests");
        buttonRequest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRequest2ActionPerformed(evt);
            }
        });

        lblBatchNum.setText("Batch Number");

        txtBatchNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDrugName)
                                .addGap(18, 18, 18)
                                .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBatchNum)
                                .addGap(18, 18, 18)
                                .addComponent(txtBatchNum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSendToQA)
                                .addComponent(buttonRequest2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelQuantity)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addGap(18, 18, 18)
                                .addComponent(txtPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnBack)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBatchNum)
                    .addComponent(txtBatchNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDrugName)
                    .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(txtPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnSendToQA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRequest2)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtDrugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugNameActionPerformed

    private void txtBatchNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchNumActionPerformed

    private void btnSendToQAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToQAActionPerformed
//        try {
//            String batchNumber = txtBatchNum.getText();
//            
////            QualityControlAndAssuranceRequest qcRequest = new QualityControlAndAssuranceRequest(
////                "Quality check for " + request.getDrugName() + " batch " + batchNumber,
////                userAccount,
////                findQualityControlReceiver(),
////                batchNumber,
////                request.getDrugName(),
////                request.getQuantity(), 
////            );
//            
//            request.setStatus("In Production - QA Check Pending");
////            organization.getWorkRequestList().addWorkRequest(qcRequest);
//            
//            JOptionPane.showMessageDialog(this, "Request sent to Quality Assurance");
//            
//            container.remove(this);
//            CardLayout layout = (CardLayout) container.getLayout();
//            layout.previous(container);
//            
//        } catch(Exception e) {
//            JOptionPane.showMessageDialog(this, "Error processing request: " + e.getMessage());
//        }
        
    }//GEN-LAST:event_btnSendToQAActionPerformed

    private void buttonRequest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRequest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRequest2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendToQA;
    private javax.swing.JButton buttonRequest2;
    private javax.swing.JLabel labelDrugName;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel lblBatchNum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtBatchNum;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtPriority;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    
    private void populateRequestDetails() {
        txtDrugName.setText(request.getDrugName());
        txtQuantity.setText(String.valueOf(request.getQuantity()));
        txtPriority.setText(request.getUrgency());
//        txtStatus.setText(request.getStatus());
        txtBatchNum.setText("BATCH-" + System.currentTimeMillis());
    }
    
    
    private UserAccount findQualityControlReceiver() {
    for(Organization org : enterprise.getOrganizationDirectory().getOrganizations()) {
        if(org instanceof QualityControlAndAssuranceOrganization) {
            for(UserAccount account : org.getUserAccountDirectory().getUserAccountList()) {
                if(account.getRole() instanceof QualityAnalystRole) {
                    return account;
                }
            }
        }
    }
    return null;
}
}
